# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

"""
Getters, setters and collaborative setters for attachments defined for model.
"""

from __future__ import annotations
import dsviper
from . import path as mp
from . import value_type as mt
from .data import *

# Namespace Tuto
# attachment<User, Account> Tuto::account
def tuto_user_account_keys(attachment_getting: dsviper.AttachmentGetting) -> Set_Tuto_UserKey:
    a = mt.attachment_Tuto_User_Account()
    return Set_Tuto_UserKey(attachment_getting.keys(a))

def tuto_user_account_diff_keys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting) -> tuple[Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey]:
    a = mt.attachment_Tuto_User_Account()
    added_keys, removed_keys, different_keys, same_keys = dsviper.AttachmentGetting.diff_keys(current, other, a)
    return Set_Tuto_UserKey(added_keys), Set_Tuto_UserKey(removed_keys), Set_Tuto_UserKey(different_keys), Set_Tuto_UserKey(same_keys)

def tuto_user_account_has(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> bool:
    a = mt.attachment_Tuto_User_Account()
    return attachment_getting.has(a, key.vpr_value)

def tuto_user_account_get(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> Optional_Tuto_Account:
    a = mt.attachment_Tuto_User_Account()
    return Optional_Tuto_Account(attachment_getting.get(a, key.vpr_value))

def tuto_user_account_set(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Account) -> None:
    a = mt.attachment_Tuto_User_Account()
    attachment_mutating.set(a, key.vpr_value, value.vpr_value)

def tuto_user_account_diff(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Account, *, recursive: bool = False) -> None:
    a = mt.attachment_Tuto_User_Account()
    attachment_mutating.diff(a, key.vpr_value, value.vpr_value, recursive=recursive)

def tuto_user_account_set_state(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Status):
    a = mt.attachment_Tuto_User_Account()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Account.state, value.vpr_value)


class _Enumerator_tuto_user_account:
    def __init__(self, attachment_getting: dsviper.AttachmentGetting):
        self.__getting = attachment_getting
        self.__iter = iter(tuto_user_account_keys(attachment_getting))

    def __iter__(self):
        return self

    def __next__(self) -> tuple[Tuto_UserKey, Tuto_Account]:
        i = next(self.__iter)
        d = tuto_user_account_get(self.__getting, i).unwrap()
        return i, d


def tuto_user_account_enumerate(attachment_getting: dsviper.AttachmentGetting) ->_Enumerator_tuto_user_account:
    return _Enumerator_tuto_user_account(attachment_getting)


# attachment<User, Thumbnail> Tuto::avatar
def tuto_user_avatar_keys(attachment_getting: dsviper.AttachmentGetting) -> Set_Tuto_UserKey:
    a = mt.attachment_Tuto_User_Avatar()
    return Set_Tuto_UserKey(attachment_getting.keys(a))

def tuto_user_avatar_diff_keys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting) -> tuple[Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey]:
    a = mt.attachment_Tuto_User_Avatar()
    added_keys, removed_keys, different_keys, same_keys = dsviper.AttachmentGetting.diff_keys(current, other, a)
    return Set_Tuto_UserKey(added_keys), Set_Tuto_UserKey(removed_keys), Set_Tuto_UserKey(different_keys), Set_Tuto_UserKey(same_keys)

def tuto_user_avatar_has(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> bool:
    a = mt.attachment_Tuto_User_Avatar()
    return attachment_getting.has(a, key.vpr_value)

def tuto_user_avatar_get(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> Optional_Tuto_Thumbnail:
    a = mt.attachment_Tuto_User_Avatar()
    return Optional_Tuto_Thumbnail(attachment_getting.get(a, key.vpr_value))

def tuto_user_avatar_set(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Thumbnail) -> None:
    a = mt.attachment_Tuto_User_Avatar()
    attachment_mutating.set(a, key.vpr_value, value.vpr_value)

def tuto_user_avatar_diff(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Thumbnail, *, recursive: bool = False) -> None:
    a = mt.attachment_Tuto_User_Avatar()
    attachment_mutating.diff(a, key.vpr_value, value.vpr_value, recursive=recursive)

def tuto_user_avatar_set_width(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: int):
    a = mt.attachment_Tuto_User_Avatar()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Thumbnail.width, value)


def tuto_user_avatar_set_height(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: int):
    a = mt.attachment_Tuto_User_Avatar()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Thumbnail.height, value)


def tuto_user_avatar_set_data(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: dsviper.ValueBlob):
    a = mt.attachment_Tuto_User_Avatar()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Thumbnail.data, value)


class _Enumerator_tuto_user_avatar:
    def __init__(self, attachment_getting: dsviper.AttachmentGetting):
        self.__getting = attachment_getting
        self.__iter = iter(tuto_user_avatar_keys(attachment_getting))

    def __iter__(self):
        return self

    def __next__(self) -> tuple[Tuto_UserKey, Tuto_Thumbnail]:
        i = next(self.__iter)
        d = tuto_user_avatar_get(self.__getting, i).unwrap()
        return i, d


def tuto_user_avatar_enumerate(attachment_getting: dsviper.AttachmentGetting) ->_Enumerator_tuto_user_avatar:
    return _Enumerator_tuto_user_avatar(attachment_getting)


# attachment<User, Identity> Tuto::identity
def tuto_user_identity_keys(attachment_getting: dsviper.AttachmentGetting) -> Set_Tuto_UserKey:
    a = mt.attachment_Tuto_User_Identity()
    return Set_Tuto_UserKey(attachment_getting.keys(a))

def tuto_user_identity_diff_keys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting) -> tuple[Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey]:
    a = mt.attachment_Tuto_User_Identity()
    added_keys, removed_keys, different_keys, same_keys = dsviper.AttachmentGetting.diff_keys(current, other, a)
    return Set_Tuto_UserKey(added_keys), Set_Tuto_UserKey(removed_keys), Set_Tuto_UserKey(different_keys), Set_Tuto_UserKey(same_keys)

def tuto_user_identity_has(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> bool:
    a = mt.attachment_Tuto_User_Identity()
    return attachment_getting.has(a, key.vpr_value)

def tuto_user_identity_get(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> Optional_Tuto_Identity:
    a = mt.attachment_Tuto_User_Identity()
    return Optional_Tuto_Identity(attachment_getting.get(a, key.vpr_value))

def tuto_user_identity_set(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Identity) -> None:
    a = mt.attachment_Tuto_User_Identity()
    attachment_mutating.set(a, key.vpr_value, value.vpr_value)

def tuto_user_identity_diff(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Identity, *, recursive: bool = False) -> None:
    a = mt.attachment_Tuto_User_Identity()
    attachment_mutating.diff(a, key.vpr_value, value.vpr_value, recursive=recursive)

def tuto_user_identity_set_firstname(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: str):
    a = mt.attachment_Tuto_User_Identity()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Identity.firstname, value)


def tuto_user_identity_set_lastname(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: str):
    a = mt.attachment_Tuto_User_Identity()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Identity.lastname, value)


class _Enumerator_tuto_user_identity:
    def __init__(self, attachment_getting: dsviper.AttachmentGetting):
        self.__getting = attachment_getting
        self.__iter = iter(tuto_user_identity_keys(attachment_getting))

    def __iter__(self):
        return self

    def __next__(self) -> tuple[Tuto_UserKey, Tuto_Identity]:
        i = next(self.__iter)
        d = tuto_user_identity_get(self.__getting, i).unwrap()
        return i, d


def tuto_user_identity_enumerate(attachment_getting: dsviper.AttachmentGetting) ->_Enumerator_tuto_user_identity:
    return _Enumerator_tuto_user_identity(attachment_getting)


# attachment<User, Login> Tuto::login
def tuto_user_login_keys(attachment_getting: dsviper.AttachmentGetting) -> Set_Tuto_UserKey:
    a = mt.attachment_Tuto_User_Login()
    return Set_Tuto_UserKey(attachment_getting.keys(a))

def tuto_user_login_diff_keys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting) -> tuple[Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey]:
    a = mt.attachment_Tuto_User_Login()
    added_keys, removed_keys, different_keys, same_keys = dsviper.AttachmentGetting.diff_keys(current, other, a)
    return Set_Tuto_UserKey(added_keys), Set_Tuto_UserKey(removed_keys), Set_Tuto_UserKey(different_keys), Set_Tuto_UserKey(same_keys)

def tuto_user_login_has(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> bool:
    a = mt.attachment_Tuto_User_Login()
    return attachment_getting.has(a, key.vpr_value)

def tuto_user_login_get(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> Optional_Tuto_Login:
    a = mt.attachment_Tuto_User_Login()
    return Optional_Tuto_Login(attachment_getting.get(a, key.vpr_value))

def tuto_user_login_set(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Login) -> None:
    a = mt.attachment_Tuto_User_Login()
    attachment_mutating.set(a, key.vpr_value, value.vpr_value)

def tuto_user_login_diff(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Login, *, recursive: bool = False) -> None:
    a = mt.attachment_Tuto_User_Login()
    attachment_mutating.diff(a, key.vpr_value, value.vpr_value, recursive=recursive)

def tuto_user_login_set_nickname(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: str):
    a = mt.attachment_Tuto_User_Login()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Login.nickname, value)


def tuto_user_login_set_password(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: str):
    a = mt.attachment_Tuto_User_Login()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Login.password, value)


class _Enumerator_tuto_user_login:
    def __init__(self, attachment_getting: dsviper.AttachmentGetting):
        self.__getting = attachment_getting
        self.__iter = iter(tuto_user_login_keys(attachment_getting))

    def __iter__(self):
        return self

    def __next__(self) -> tuple[Tuto_UserKey, Tuto_Login]:
        i = next(self.__iter)
        d = tuto_user_login_get(self.__getting, i).unwrap()
        return i, d


def tuto_user_login_enumerate(attachment_getting: dsviper.AttachmentGetting) ->_Enumerator_tuto_user_login:
    return _Enumerator_tuto_user_login(attachment_getting)


# attachment<User, Texture> Tuto::portrait
def tuto_user_portrait_keys(attachment_getting: dsviper.AttachmentGetting) -> Set_Tuto_UserKey:
    a = mt.attachment_Tuto_User_Portrait()
    return Set_Tuto_UserKey(attachment_getting.keys(a))

def tuto_user_portrait_diff_keys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting) -> tuple[Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey,Set_Tuto_UserKey]:
    a = mt.attachment_Tuto_User_Portrait()
    added_keys, removed_keys, different_keys, same_keys = dsviper.AttachmentGetting.diff_keys(current, other, a)
    return Set_Tuto_UserKey(added_keys), Set_Tuto_UserKey(removed_keys), Set_Tuto_UserKey(different_keys), Set_Tuto_UserKey(same_keys)

def tuto_user_portrait_has(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> bool:
    a = mt.attachment_Tuto_User_Portrait()
    return attachment_getting.has(a, key.vpr_value)

def tuto_user_portrait_get(attachment_getting: dsviper.AttachmentGetting, key: Tuto_UserKey) -> Optional_Tuto_Texture:
    a = mt.attachment_Tuto_User_Portrait()
    return Optional_Tuto_Texture(attachment_getting.get(a, key.vpr_value))

def tuto_user_portrait_set(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Texture) -> None:
    a = mt.attachment_Tuto_User_Portrait()
    attachment_mutating.set(a, key.vpr_value, value.vpr_value)

def tuto_user_portrait_diff(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: Tuto_Texture, *, recursive: bool = False) -> None:
    a = mt.attachment_Tuto_User_Portrait()
    attachment_mutating.diff(a, key.vpr_value, value.vpr_value, recursive=recursive)

def tuto_user_portrait_set_width(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: int):
    a = mt.attachment_Tuto_User_Portrait()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Texture.width, value)


def tuto_user_portrait_set_height(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: int):
    a = mt.attachment_Tuto_User_Portrait()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Texture.height, value)


def tuto_user_portrait_set_pixels(attachment_mutating: dsviper.AttachmentMutating, key: Tuto_UserKey, value: dsviper.ValueBlobId):
    a = mt.attachment_Tuto_User_Portrait()
    attachment_mutating.update(a, key.vpr_value, mp.Tuto_Path_Texture.pixels, value)


class _Enumerator_tuto_user_portrait:
    def __init__(self, attachment_getting: dsviper.AttachmentGetting):
        self.__getting = attachment_getting
        self.__iter = iter(tuto_user_portrait_keys(attachment_getting))

    def __iter__(self):
        return self

    def __next__(self) -> tuple[Tuto_UserKey, Tuto_Texture]:
        i = next(self.__iter)
        d = tuto_user_portrait_get(self.__getting, i).unwrap()
        return i, d


def tuto_user_portrait_enumerate(attachment_getting: dsviper.AttachmentGetting) ->_Enumerator_tuto_user_portrait:
    return _Enumerator_tuto_user_portrait(attachment_getting)


