# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

"""
Python classes for concepts, clubs, enums and structs defined for model.
"""

from __future__ import annotations
import dsviper
import typing
from . import value_type as mt
from . import definitions as md

T = typing.TypeVar("T")
R = typing.TypeVar("R")

class classproperty(typing.Generic[T, R]):
    def __init__(self, func: typing.Callable[[type[T]], R]) -> None:
        self.func = func

    def __get__(self, obj: typing.Any, cls: type[T]) -> R:
        return self.func(cls)


class Proxy:

    __slots__ = ["vpr_value"]

    def __init__(self, vpr_value):
        self.vpr_value = vpr_value

    def __hash__(self) -> int:
        return hash(self.vpr_value)

    def __repr__(self) -> str:
        return repr(self.vpr_value)

    def __lt__(self, other: Proxy) -> bool:
        return self.vpr_value < other.vpr_value

    def __le__(self, other: Proxy) -> bool:
        return self.vpr_value <= other.vpr_value

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Proxy):
            return NotImplemented
        return self.vpr_value == other.vpr_value

    def __ne__(self, other: object) -> bool:
        if not isinstance(other, Proxy):
            return NotImplemented
        return self.vpr_value != other.vpr_value

    def __gt__(self, other: Proxy) -> bool:
        return self.vpr_value > other.vpr_value

    def __ge__(self, other: Proxy) -> bool:
        return self.vpr_value >= other.vpr_value

    def encode(self, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) -> dsviper.ValueBlob:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        return dsviper.Value.encode(self.vpr_value, stream_codec_instancing=stream_codec_instancing)

    def write(self, stream_writing: dsviper.StreamWriting) -> None:
        return dsviper.Value.write(self.vpr_value, stream_writing)

    def hexdigest(self) -> str:
        return dsviper.Value.hexdigest(self.vpr_value)

# AnyConceptKey
class AnyConceptKey(Proxy):
    """A proxy class for a key<any_concept>."""

    __slots__ = []

    def __init__(self, value):
        if not isinstance(value, dsviper.ValueKey):
            raise TypeError("value is not a Key")
        if not dsviper.ValueKey.cast(value).type_key().is_any_concept():
            raise ValueError("value is not a Key for any_concept")
        super().__init__(value)

    def __repr__(self) -> str:
        return self.description()

    def instance_id(self) -> dsviper.ValueUUId:
        return self.vpr_value.instance_id()

    def runtime_id(self) -> dsviper.ValueUUId:
        return self.vpr_value.type_concept().runtime_id()

    def description(self) -> str:
        match self.runtime_id():
            case md.RuntimeIds.Tuto_User:
                return f'{self.instance_id().encoded()}:AnyConceptKey(Tuto::UserKey)'
            case _:
                return f'{self.instance_id().encoded()}:AnyConceptKey({self.runtime_id().encoded()})'

    def is_known(self) -> bool:
        match self.runtime_id():
            case md.RuntimeIds.Tuto_User:
                return True
            case _:
                return False

    def is_valid(self) -> bool:
        return self.instance_id().is_valid()

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->AnyConceptKey:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueKey.cast(dsviper.Value.decode(blob, mt.type_AnyConceptKey(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return AnyConceptKey(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) ->AnyConceptKey:
        value = dsviper.ValueKey.cast(dsviper.Value.read(mt.type_AnyConceptKey(), stream_reading, md.definitions()))
        return AnyConceptKey(value)

# Namespace Tuto
# concept Tuto::UserKey
class Tuto_UserKey(Proxy):
    """
    [A proxy class for a key<Tuto::UserKey>]

    A user.
    """

    __slots__ = []

    def __init__(self, identifier: dsviper.ValueKey | dsviper.ValueUUId | str):
        if isinstance(identifier, dsviper.ValueKey):
            if identifier.type() != mt.type_Tuto_UserKey():
                raise TypeError("identifier is not a Tuto::UserKey")
            super().__init__(identifier)
        elif isinstance(identifier, str) or isinstance(identifier, dsviper.ValueUUId):
            super().__init__(dsviper.ValueKey.create(mt.type_check_Tuto_UserKey(), identifier))
        else:
            raise TypeError("identifier must be a ValueKey, a ValueUUId or a str.")

    def __repr__(self) -> str:
        return self.description()

    @staticmethod
    def create() -> Tuto_UserKey:
        return Tuto_UserKey(dsviper.ValueUUId.create())

    @staticmethod
    def from_any_concept_key(key: AnyConceptKey) -> Tuto_UserKey | None:
        match key.runtime_id():
            case md.RuntimeIds.Tuto_User:
                return Tuto_UserKey(key.instance_id())
            case _:
                return None

    def to_any_concept_key(self) -> AnyConceptKey:
        return AnyConceptKey(self.vpr_value.to_any_concept_key())

    def instance_id(self) -> dsviper.ValueUUId:
        return self.vpr_value.instance_id()

    def runtime_id(self) -> dsviper.ValueUUId:
        return self.vpr_value.type_concept().runtime_id()

    def description(self) -> str:
        match self.runtime_id():
            case  md.RuntimeIds.Tuto_User:
                return f'{self.instance_id().encoded()}:Tuto::UserKey'
            case _:
                return f'{self.instance_id().encoded()}:Tuto::UserKey({self.runtime_id()})'

    def is_known(self) -> bool:
        match self.runtime_id():
            case md.RuntimeIds.Tuto_User:
                return True
            case _:
                return False

    def is_valid(self) -> bool:
        return self.instance_id().is_valid()

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) -> Tuto_UserKey:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueKey.cast(dsviper.Value.decode(blob, mt.type_Tuto_UserKey(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Tuto_UserKey(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Tuto_UserKey:
        value = dsviper.ValueKey.cast(dsviper.Value.read(mt.type_Tuto_UserKey(), stream_reading, md.definitions()))
        return Tuto_UserKey(value)

# enum Tuto::Status
class Tuto_Status(Proxy):
    """
    [A proxy class for enum Tuto::Status]

    Lifecycle state of a User account.
    """

    __slots__ = []

    def __init__(self, value):
        if value.type() != mt.type_Tuto_Status():
            raise TypeError("value is not a Tuto::Status")
        super().__init__(value)

    @classproperty
    def PENDING(self) -> Tuto_Status:
        """a proxy for the viper enumeration case .pending"""
        if not hasattr(self, "__PENDING"):
            value = dsviper.ValueEnumeration(mt.type_Tuto_Status(), "pending")
            setattr(self, "__PENDING", Tuto_Status(value))
        return getattr(self, "__PENDING")

    @classproperty
    def ACTIVE(self) -> Tuto_Status:
        """a proxy for the viper enumeration case .active"""
        if not hasattr(self, "__ACTIVE"):
            value = dsviper.ValueEnumeration(mt.type_Tuto_Status(), "active")
            setattr(self, "__ACTIVE", Tuto_Status(value))
        return getattr(self, "__ACTIVE")

    @classproperty
    def COMPLETED(self) -> Tuto_Status:
        """a proxy for the viper enumeration case .completed"""
        if not hasattr(self, "__COMPLETED"):
            value = dsviper.ValueEnumeration(mt.type_Tuto_Status(), "completed")
            setattr(self, "__COMPLETED", Tuto_Status(value))
        return getattr(self, "__COMPLETED")


    def name(self) -> str:
        return self.vpr_value.name()

    @staticmethod
    def from_str(name: str):
        if not isinstance(name, str):
            raise TypeError(f'name must be a str.')
        match name:
            case "pending":
                return Tuto_Status.PENDING
            case "active":
                return Tuto_Status.ACTIVE
            case "completed":
                return Tuto_Status.COMPLETED
            case _:
                raise ValueError(f'unknown enumeration case {name}')

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) -> Tuto_Status:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueEnumeration.cast(dsviper.Value.decode(blob, mt.type_Tuto_Status(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Tuto_Status(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Tuto_Status:
        value = dsviper.ValueEnumeration.cast(dsviper.Value.read(mt.type_Tuto_Status(), stream_reading, md.definitions()))
        return Tuto_Status(value)

# struct Tuto::Account
class Tuto_Account(Proxy):
    """
    [A proxy class for struct Tuto::Account]

    Account state for a User.
    """

    __slots__ = ()

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueStructure):
            if value.type() != mt.type_Tuto_Account():
                raise TypeError("value is not a Tuto::Account")
            super().__init__(value)
        else:
            super().__init__(dsviper.ValueStructure(mt.type_Tuto_Account(), value))

    @property
    def state(self) -> Tuto_Status:
        v = self.vpr_value.at("state")
        return Tuto_Status(v)

    @state.setter
    def state(self, value: Tuto_Status) -> None:
        self.vpr_value.set("state", value.vpr_value)


    def copy(self) -> Tuto_Account:
        return Tuto_Account(self.vpr_value.copy())

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None, pack_sized: bool = False) -> Tuto_Account:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Tuto_Account(), md.definitions(), stream_codec_instancing=stream_codec_instancing, pack_sized=pack_sized))
        return Tuto_Account(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading, pack_sized: bool = False) -> Tuto_Account:
        value = dsviper.ValueStructure.cast(dsviper.Value.read(mt.type_Tuto_Account(), stream_reading, md.definitions(), pack_sized=pack_sized))
        return Tuto_Account(value)

# struct Tuto::Identity
class Tuto_Identity(Proxy):
    """
    [A proxy class for struct Tuto::Identity]

    Identity information for a User.
    """

    __slots__ = ()

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueStructure):
            if value.type() != mt.type_Tuto_Identity():
                raise TypeError("value is not a Tuto::Identity")
            super().__init__(value)
        else:
            super().__init__(dsviper.ValueStructure(mt.type_Tuto_Identity(), value))

    @property
    def firstname(self) -> str:
        v = self.vpr_value.at("firstname")
        return v

    @firstname.setter
    def firstname(self, value: str) -> None:
        self.vpr_value.set("firstname", value)

    @property
    def lastname(self) -> str:
        v = self.vpr_value.at("lastname")
        return v

    @lastname.setter
    def lastname(self, value: str) -> None:
        self.vpr_value.set("lastname", value)


    def copy(self) -> Tuto_Identity:
        return Tuto_Identity(self.vpr_value.copy())

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None, pack_sized: bool = False) -> Tuto_Identity:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Tuto_Identity(), md.definitions(), stream_codec_instancing=stream_codec_instancing, pack_sized=pack_sized))
        return Tuto_Identity(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading, pack_sized: bool = False) -> Tuto_Identity:
        value = dsviper.ValueStructure.cast(dsviper.Value.read(mt.type_Tuto_Identity(), stream_reading, md.definitions(), pack_sized=pack_sized))
        return Tuto_Identity(value)

# struct Tuto::Login
class Tuto_Login(Proxy):
    """
    [A proxy class for struct Tuto::Login]

    Login credentials for a User.
    """

    __slots__ = ()

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueStructure):
            if value.type() != mt.type_Tuto_Login():
                raise TypeError("value is not a Tuto::Login")
            super().__init__(value)
        else:
            super().__init__(dsviper.ValueStructure(mt.type_Tuto_Login(), value))

    @property
    def nickname(self) -> str:
        v = self.vpr_value.at("nickname")
        return v

    @nickname.setter
    def nickname(self, value: str) -> None:
        self.vpr_value.set("nickname", value)

    @property
    def password(self) -> str:
        v = self.vpr_value.at("password")
        return v

    @password.setter
    def password(self, value: str) -> None:
        self.vpr_value.set("password", value)


    def copy(self) -> Tuto_Login:
        return Tuto_Login(self.vpr_value.copy())

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None, pack_sized: bool = False) -> Tuto_Login:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Tuto_Login(), md.definitions(), stream_codec_instancing=stream_codec_instancing, pack_sized=pack_sized))
        return Tuto_Login(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading, pack_sized: bool = False) -> Tuto_Login:
        value = dsviper.ValueStructure.cast(dsviper.Value.read(mt.type_Tuto_Login(), stream_reading, md.definitions(), pack_sized=pack_sized))
        return Tuto_Login(value)

# struct Tuto::Texture
class Tuto_Texture(Proxy):
    """
    [A proxy class for struct Tuto::Texture]

    A high-resolution texture stored by reference.
    """

    __slots__ = ()

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueStructure):
            if value.type() != mt.type_Tuto_Texture():
                raise TypeError("value is not a Tuto::Texture")
            super().__init__(value)
        else:
            super().__init__(dsviper.ValueStructure(mt.type_Tuto_Texture(), value))

    @property
    def width(self) -> int:
        v = self.vpr_value.at("width")
        return v

    @width.setter
    def width(self, value: int) -> None:
        self.vpr_value.set("width", value)

    @property
    def height(self) -> int:
        v = self.vpr_value.at("height")
        return v

    @height.setter
    def height(self, value: int) -> None:
        self.vpr_value.set("height", value)

    @property
    def pixels(self) -> dsviper.ValueBlobId:
        v = self.vpr_value.at("pixels")
        return v

    @pixels.setter
    def pixels(self, value: dsviper.ValueBlobId) -> None:
        self.vpr_value.set("pixels", value)


    def copy(self) -> Tuto_Texture:
        return Tuto_Texture(self.vpr_value.copy())

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None, pack_sized: bool = False) -> Tuto_Texture:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Tuto_Texture(), md.definitions(), stream_codec_instancing=stream_codec_instancing, pack_sized=pack_sized))
        return Tuto_Texture(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading, pack_sized: bool = False) -> Tuto_Texture:
        value = dsviper.ValueStructure.cast(dsviper.Value.read(mt.type_Tuto_Texture(), stream_reading, md.definitions(), pack_sized=pack_sized))
        return Tuto_Texture(value)

# struct Tuto::Thumbnail
class Tuto_Thumbnail(Proxy):
    """
    [A proxy class for struct Tuto::Thumbnail]

    A small avatar image stored inline.
    """

    __slots__ = ()

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueStructure):
            if value.type() != mt.type_Tuto_Thumbnail():
                raise TypeError("value is not a Tuto::Thumbnail")
            super().__init__(value)
        else:
            super().__init__(dsviper.ValueStructure(mt.type_Tuto_Thumbnail(), value))

    @property
    def width(self) -> int:
        v = self.vpr_value.at("width")
        return v

    @width.setter
    def width(self, value: int) -> None:
        self.vpr_value.set("width", value)

    @property
    def height(self) -> int:
        v = self.vpr_value.at("height")
        return v

    @height.setter
    def height(self, value: int) -> None:
        self.vpr_value.set("height", value)

    @property
    def data(self) -> dsviper.ValueBlob:
        v = self.vpr_value.at("data")
        return v

    @data.setter
    def data(self, value: dsviper.ValueBlob) -> None:
        self.vpr_value.set("data", value)


    def copy(self) -> Tuto_Thumbnail:
        return Tuto_Thumbnail(self.vpr_value.copy())

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None, pack_sized: bool = False) -> Tuto_Thumbnail:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Tuto_Thumbnail(), md.definitions(), stream_codec_instancing=stream_codec_instancing, pack_sized=pack_sized))
        return Tuto_Thumbnail(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading, pack_sized: bool = False) -> Tuto_Thumbnail:
        value = dsviper.ValueStructure.cast(dsviper.Value.read(mt.type_Tuto_Thumbnail(), stream_reading, md.definitions(), pack_sized=pack_sized))
        return Tuto_Thumbnail(value)

# optional<any_concept>
class Optional_AnyConceptKey(Proxy):
    """[A proxy class for optional<any_concept>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_AnyConceptKey():
                raise TypeError("value is not a optional<any_concept>")
            super().__init__(value)
        elif isinstance(value, AnyConceptKey):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_AnyConceptKey(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_AnyConceptKey(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> AnyConceptKey:
        v = self.vpr_value.unwrap()
        return AnyConceptKey(v)

    def get(self, default: AnyConceptKey | None = None) -> AnyConceptKey:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return AnyConceptKey(v)

    def copy(self) -> Optional_AnyConceptKey:
        return Optional_AnyConceptKey(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_AnyConceptKey:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_AnyConceptKey(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_AnyConceptKey(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_AnyConceptKey:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_AnyConceptKey(), stream_reading, md.definitions()))
        return Optional_AnyConceptKey(value)

# optional<Tuto::Account>
class Optional_Tuto_Account(Proxy):
    """[A proxy class for optional<Tuto::Account>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_Tuto_Account():
                raise TypeError("value is not a optional<Tuto::Account>")
            super().__init__(value)
        elif isinstance(value, Tuto_Account):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Account(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Account(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> Tuto_Account:
        v = self.vpr_value.unwrap()
        return Tuto_Account(v)

    def get(self, default: Tuto_Account | None = None) -> Tuto_Account:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return Tuto_Account(v)

    def copy(self) -> Optional_Tuto_Account:
        return Optional_Tuto_Account(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_Tuto_Account:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Tuto_Account(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_Tuto_Account(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_Tuto_Account:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_Tuto_Account(), stream_reading, md.definitions()))
        return Optional_Tuto_Account(value)

# optional<Tuto::Identity>
class Optional_Tuto_Identity(Proxy):
    """[A proxy class for optional<Tuto::Identity>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_Tuto_Identity():
                raise TypeError("value is not a optional<Tuto::Identity>")
            super().__init__(value)
        elif isinstance(value, Tuto_Identity):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Identity(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Identity(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> Tuto_Identity:
        v = self.vpr_value.unwrap()
        return Tuto_Identity(v)

    def get(self, default: Tuto_Identity | None = None) -> Tuto_Identity:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return Tuto_Identity(v)

    def copy(self) -> Optional_Tuto_Identity:
        return Optional_Tuto_Identity(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_Tuto_Identity:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Tuto_Identity(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_Tuto_Identity(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_Tuto_Identity:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_Tuto_Identity(), stream_reading, md.definitions()))
        return Optional_Tuto_Identity(value)

# optional<Tuto::Login>
class Optional_Tuto_Login(Proxy):
    """[A proxy class for optional<Tuto::Login>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_Tuto_Login():
                raise TypeError("value is not a optional<Tuto::Login>")
            super().__init__(value)
        elif isinstance(value, Tuto_Login):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Login(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Login(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> Tuto_Login:
        v = self.vpr_value.unwrap()
        return Tuto_Login(v)

    def get(self, default: Tuto_Login | None = None) -> Tuto_Login:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return Tuto_Login(v)

    def copy(self) -> Optional_Tuto_Login:
        return Optional_Tuto_Login(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_Tuto_Login:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Tuto_Login(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_Tuto_Login(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_Tuto_Login:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_Tuto_Login(), stream_reading, md.definitions()))
        return Optional_Tuto_Login(value)

# optional<Tuto::Texture>
class Optional_Tuto_Texture(Proxy):
    """[A proxy class for optional<Tuto::Texture>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_Tuto_Texture():
                raise TypeError("value is not a optional<Tuto::Texture>")
            super().__init__(value)
        elif isinstance(value, Tuto_Texture):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Texture(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Texture(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> Tuto_Texture:
        v = self.vpr_value.unwrap()
        return Tuto_Texture(v)

    def get(self, default: Tuto_Texture | None = None) -> Tuto_Texture:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return Tuto_Texture(v)

    def copy(self) -> Optional_Tuto_Texture:
        return Optional_Tuto_Texture(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_Tuto_Texture:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Tuto_Texture(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_Tuto_Texture(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_Tuto_Texture:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_Tuto_Texture(), stream_reading, md.definitions()))
        return Optional_Tuto_Texture(value)

# optional<Tuto::Thumbnail>
class Optional_Tuto_Thumbnail(Proxy):
    """[A proxy class for optional<Tuto::Thumbnail>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_Tuto_Thumbnail():
                raise TypeError("value is not a optional<Tuto::Thumbnail>")
            super().__init__(value)
        elif isinstance(value, Tuto_Thumbnail):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Thumbnail(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_Thumbnail(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> Tuto_Thumbnail:
        v = self.vpr_value.unwrap()
        return Tuto_Thumbnail(v)

    def get(self, default: Tuto_Thumbnail | None = None) -> Tuto_Thumbnail:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return Tuto_Thumbnail(v)

    def copy(self) -> Optional_Tuto_Thumbnail:
        return Optional_Tuto_Thumbnail(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_Tuto_Thumbnail:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Tuto_Thumbnail(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_Tuto_Thumbnail(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_Tuto_Thumbnail:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_Tuto_Thumbnail(), stream_reading, md.definitions()))
        return Optional_Tuto_Thumbnail(value)

# optional<Tuto::User>
class Optional_Tuto_UserKey(Proxy):
    """[A proxy class for optional<Tuto::User>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueOptional):
            if value.type() != mt.type_optional_Tuto_UserKey():
                raise TypeError("value is not a optional<Tuto::User>")
            super().__init__(value)
        elif isinstance(value, Tuto_UserKey):
            v = value.vpr_value
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_UserKey(), v))
        else:
            super().__init__(dsviper.ValueOptional(mt.type_optional_Tuto_UserKey(), value))

    def __bool__(self) -> bool:
        return not self.is_nil()

    def is_nil(self) -> bool:
        return self.vpr_value.is_nil()

    def wrap(self, value) -> None:
        self.vpr_value.wrap(value.vpr_value)

    def unwrap(self) -> Tuto_UserKey:
        v = self.vpr_value.unwrap()
        return Tuto_UserKey(v)

    def get(self, default: Tuto_UserKey | None = None) -> Tuto_UserKey:
        if default is None:
            v = self.vpr_value.unwrap()
        else:
            d = default.vpr_value
            v = self.vpr_value.get(d)
        return Tuto_UserKey(v)

    def copy(self) -> Optional_Tuto_UserKey:
        return Optional_Tuto_UserKey(dsviper.Value.copy(self.vpr_value))

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Optional_Tuto_UserKey:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Tuto_UserKey(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Optional_Tuto_UserKey(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Optional_Tuto_UserKey:
        value = dsviper.ValueOptional.cast(dsviper.Value.read(mt.type_optional_Tuto_UserKey(), stream_reading, md.definitions()))
        return Optional_Tuto_UserKey(value)

# set<Tuto::User>
class Set_Tuto_UserKey(Proxy):
    """[A proxy class for set<Tuto::User>]"""

    __slots__ = []

    def __init__(self, value=None):
        if isinstance(value, dsviper.ValueSet):
            if value.type() != mt.type_set_Tuto_UserKey():
                raise TypeError("value is not a set<Tuto::User>")
            super().__init__(value)
        else:
            super().__init__(dsviper.ValueSet(mt.type_set_Tuto_UserKey(), value))

    def __iter__(self) -> typing.Iterator[Tuto_UserKey]:
        return Set_Tuto_UserKey_Iter(self)

    def __len__(self) -> int:
        return len(self.vpr_value)

    def __getitem__(self, item: int) -> Tuto_UserKey:
        v = self.vpr_value[item]
        return Tuto_UserKey(v)

    def __contains__(self, value: Tuto_UserKey) -> bool:
        v = value.vpr_value
        return v in self.vpr_value

    def __and__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return self.intersection(other)

    def __iand__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        self.intersection_update(other)
        return self

    def __or__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return self.union(other)

    def __ior__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        self.update(other)
        return self

    def __sub__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return self.difference(other)

    def __isub__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        self.difference_update(other)
        return self

    def __xor__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return self.symmetric_difference(other)

    def __ixor__(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        self.symmetric_difference_update(other)
        return self

    def add(self, value: Tuto_UserKey) -> None:
        self.vpr_value.add(value.vpr_value)

    def clear(self) -> None:
        self.vpr_value.clear()

    def copy(self) -> Set_Tuto_UserKey:
        return Set_Tuto_UserKey(self.vpr_value.copy())

    def difference(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return Set_Tuto_UserKey(self.vpr_value.difference(other.vpr_value))

    def difference_update(self, other: Set_Tuto_UserKey) -> None:
        self.vpr_value.difference_update(other.vpr_value)

    def discard(self, value: Tuto_UserKey) -> None:
        self.vpr_value.discard(value.vpr_value)

    def intersection(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return Set_Tuto_UserKey(self.vpr_value.intersection(other.vpr_value))

    def intersection_update(self, other: Set_Tuto_UserKey) -> None:
        self.vpr_value.intersection_update(other.vpr_value)

    def isdisjoint(self, other: Set_Tuto_UserKey) -> bool:
        return self.vpr_value.isdisjoint(other.vpr_value)

    def issubset(self, other: Set_Tuto_UserKey) -> bool:
        return self.vpr_value.issubset(other.vpr_value)

    def issuperset(self, other: Set_Tuto_UserKey) -> bool:
        return self.vpr_value.issuperset(other.vpr_value)

    def pop(self) -> Tuto_UserKey:
        v = self.vpr_value.pop()
        return Tuto_UserKey(v)

    def remove(self, value: Tuto_UserKey) -> None:
        return self.vpr_value.remove(value.vpr_value)

    def symmetric_difference(self, other: Set_Tuto_UserKey) ->  Set_Tuto_UserKey:
        return Set_Tuto_UserKey(self.vpr_value.symmetric_difference(other.vpr_value))

    def symmetric_difference_update(self, other: Set_Tuto_UserKey) -> None:
        self.vpr_value.symmetric_difference_update(other.vpr_value)

    def union(self, other: Set_Tuto_UserKey) -> Set_Tuto_UserKey:
        return Set_Tuto_UserKey(self.vpr_value.union(other.vpr_value))

    def update(self, other: Set_Tuto_UserKey) -> None:
        self.vpr_value.update(other.vpr_value)

    def min(self) -> Tuto_UserKey:
        v = self.vpr_value.min()
        return Tuto_UserKey(v)

    def max(self) -> Tuto_UserKey:
        v = self.vpr_value.max()
        return Tuto_UserKey(v)

    @staticmethod
    def decode(blob: dsviper.ValueBlob, *, stream_codec_instancing: dsviper.StreamCodecInstancing | None = None) ->Set_Tuto_UserKey:
        stream_codec_instancing = stream_codec_instancing if stream_codec_instancing is not None else dsviper.Codec.STREAM_BINARY
        value = dsviper.ValueSet.cast(dsviper.Value.decode(blob, mt.type_set_Tuto_UserKey(), md.definitions(), stream_codec_instancing=stream_codec_instancing))
        return Set_Tuto_UserKey(value)

    @staticmethod
    def read(stream_reading: dsviper.StreamReading) -> Set_Tuto_UserKey:
        value = dsviper.ValueSet.cast(dsviper.Value.read(mt.type_set_Tuto_UserKey(), stream_reading, md.definitions()))
        return Set_Tuto_UserKey(value)


class Set_Tuto_UserKey_Iter:
    def __init__(self, value: Set_Tuto_UserKey):
        self.__iter = iter(value.vpr_value)

    def __iter__(self):
        return self

    def __next__(self) -> Tuto_UserKey:
        v = next(self.__iter)
        return Tuto_UserKey(v)




__all__ = [
    "AnyConceptKey",
    "Tuto_UserKey",
    "Tuto_Status",
    "Tuto_Account",
    "Tuto_Identity",
    "Tuto_Login",
    "Tuto_Texture",
    "Tuto_Thumbnail",
    "Optional_AnyConceptKey",
    "Optional_Tuto_Account",
    "Optional_Tuto_Identity",
    "Optional_Tuto_Login",
    "Optional_Tuto_Texture",
    "Optional_Tuto_Thumbnail",
    "Optional_Tuto_UserKey",
    "Set_Tuto_UserKey",
]

