# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

"""
Getters and setters for attachments defined for model.
"""

from __future__ import annotations
import dsviper
from . import definitions as md
from .data import *

# Namespace Tuto
# attachment<User, Account> Tuto::account
def tuto_user_account_keys(database: dsviper.Database) -> Set_Tuto_UserKey:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Account)
    return Set_Tuto_UserKey(database.keys(a))

def tuto_user_account_has(database: dsviper.Database, key: Tuto_UserKey) -> bool:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Account)
    return database.has(a, key.vpr_value)

def tuto_user_account_get(database: dsviper.Database, key: Tuto_UserKey) -> Optional_Tuto_Account:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Account)
    return Optional_Tuto_Account(database.get(a, key.vpr_value))

def tuto_user_account_set(database: dsviper.Database, key: Tuto_UserKey, value: Tuto_Account) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Account)
    database.set(a, key.vpr_value, value.vpr_value)

def tuto_user_account_del(database: dsviper.Database, key: Tuto_UserKey) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Account)
    database.delete(a, key.vpr_value)

class _Enumerator_tuto_user_account:
    def __init__(self, database: dsviper.Database):
        self.__databasing = database
        self.__iter = iter(tuto_user_account_keys(database))

    def __iter__(self):
        return self

    def  __next__(self) -> tuple[Tuto_UserKey, Tuto_Account]:
        i = next(self.__iter)
        d = tuto_user_account_get(self.__databasing, i).unwrap()
        return i, d


def tuto_user_account_enumerate(database: dsviper.Database) ->_Enumerator_tuto_user_account:
    return _Enumerator_tuto_user_account(database)


# attachment<User, Thumbnail> Tuto::avatar
def tuto_user_avatar_keys(database: dsviper.Database) -> Set_Tuto_UserKey:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Avatar)
    return Set_Tuto_UserKey(database.keys(a))

def tuto_user_avatar_has(database: dsviper.Database, key: Tuto_UserKey) -> bool:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Avatar)
    return database.has(a, key.vpr_value)

def tuto_user_avatar_get(database: dsviper.Database, key: Tuto_UserKey) -> Optional_Tuto_Thumbnail:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Avatar)
    return Optional_Tuto_Thumbnail(database.get(a, key.vpr_value))

def tuto_user_avatar_set(database: dsviper.Database, key: Tuto_UserKey, value: Tuto_Thumbnail) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Avatar)
    database.set(a, key.vpr_value, value.vpr_value)

def tuto_user_avatar_del(database: dsviper.Database, key: Tuto_UserKey) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Avatar)
    database.delete(a, key.vpr_value)

class _Enumerator_tuto_user_avatar:
    def __init__(self, database: dsviper.Database):
        self.__databasing = database
        self.__iter = iter(tuto_user_avatar_keys(database))

    def __iter__(self):
        return self

    def  __next__(self) -> tuple[Tuto_UserKey, Tuto_Thumbnail]:
        i = next(self.__iter)
        d = tuto_user_avatar_get(self.__databasing, i).unwrap()
        return i, d


def tuto_user_avatar_enumerate(database: dsviper.Database) ->_Enumerator_tuto_user_avatar:
    return _Enumerator_tuto_user_avatar(database)


# attachment<User, Identity> Tuto::identity
def tuto_user_identity_keys(database: dsviper.Database) -> Set_Tuto_UserKey:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Identity)
    return Set_Tuto_UserKey(database.keys(a))

def tuto_user_identity_has(database: dsviper.Database, key: Tuto_UserKey) -> bool:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Identity)
    return database.has(a, key.vpr_value)

def tuto_user_identity_get(database: dsviper.Database, key: Tuto_UserKey) -> Optional_Tuto_Identity:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Identity)
    return Optional_Tuto_Identity(database.get(a, key.vpr_value))

def tuto_user_identity_set(database: dsviper.Database, key: Tuto_UserKey, value: Tuto_Identity) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Identity)
    database.set(a, key.vpr_value, value.vpr_value)

def tuto_user_identity_del(database: dsviper.Database, key: Tuto_UserKey) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Identity)
    database.delete(a, key.vpr_value)

class _Enumerator_tuto_user_identity:
    def __init__(self, database: dsviper.Database):
        self.__databasing = database
        self.__iter = iter(tuto_user_identity_keys(database))

    def __iter__(self):
        return self

    def  __next__(self) -> tuple[Tuto_UserKey, Tuto_Identity]:
        i = next(self.__iter)
        d = tuto_user_identity_get(self.__databasing, i).unwrap()
        return i, d


def tuto_user_identity_enumerate(database: dsviper.Database) ->_Enumerator_tuto_user_identity:
    return _Enumerator_tuto_user_identity(database)


# attachment<User, Login> Tuto::login
def tuto_user_login_keys(database: dsviper.Database) -> Set_Tuto_UserKey:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Login)
    return Set_Tuto_UserKey(database.keys(a))

def tuto_user_login_has(database: dsviper.Database, key: Tuto_UserKey) -> bool:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Login)
    return database.has(a, key.vpr_value)

def tuto_user_login_get(database: dsviper.Database, key: Tuto_UserKey) -> Optional_Tuto_Login:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Login)
    return Optional_Tuto_Login(database.get(a, key.vpr_value))

def tuto_user_login_set(database: dsviper.Database, key: Tuto_UserKey, value: Tuto_Login) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Login)
    database.set(a, key.vpr_value, value.vpr_value)

def tuto_user_login_del(database: dsviper.Database, key: Tuto_UserKey) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Login)
    database.delete(a, key.vpr_value)

class _Enumerator_tuto_user_login:
    def __init__(self, database: dsviper.Database):
        self.__databasing = database
        self.__iter = iter(tuto_user_login_keys(database))

    def __iter__(self):
        return self

    def  __next__(self) -> tuple[Tuto_UserKey, Tuto_Login]:
        i = next(self.__iter)
        d = tuto_user_login_get(self.__databasing, i).unwrap()
        return i, d


def tuto_user_login_enumerate(database: dsviper.Database) ->_Enumerator_tuto_user_login:
    return _Enumerator_tuto_user_login(database)


# attachment<User, Texture> Tuto::portrait
def tuto_user_portrait_keys(database: dsviper.Database) -> Set_Tuto_UserKey:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Portrait)
    return Set_Tuto_UserKey(database.keys(a))

def tuto_user_portrait_has(database: dsviper.Database, key: Tuto_UserKey) -> bool:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Portrait)
    return database.has(a, key.vpr_value)

def tuto_user_portrait_get(database: dsviper.Database, key: Tuto_UserKey) -> Optional_Tuto_Texture:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Portrait)
    return Optional_Tuto_Texture(database.get(a, key.vpr_value))

def tuto_user_portrait_set(database: dsviper.Database, key: Tuto_UserKey, value: Tuto_Texture) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Portrait)
    database.set(a, key.vpr_value, value.vpr_value)

def tuto_user_portrait_del(database: dsviper.Database, key: Tuto_UserKey) -> None:
    a = database.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Portrait)
    database.delete(a, key.vpr_value)

class _Enumerator_tuto_user_portrait:
    def __init__(self, database: dsviper.Database):
        self.__databasing = database
        self.__iter = iter(tuto_user_portrait_keys(database))

    def __iter__(self):
        return self

    def  __next__(self) -> tuple[Tuto_UserKey, Tuto_Texture]:
        i = next(self.__iter)
        d = tuto_user_portrait_get(self.__databasing, i).unwrap()
        return i, d


def tuto_user_portrait_enumerate(database: dsviper.Database) ->_Enumerator_tuto_user_portrait:
    return _Enumerator_tuto_user_portrait(database)


