# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

"""
Viper Definitions and runtime ID for model.
"""

from __future__ import annotations
import zlib
import base64
import dsviper
from . import resources as mr

# Definitions
_DEFINITIONS = None

def definitions() -> dsviper.DefinitionsConst:
    global _DEFINITIONS
    if _DEFINITIONS is None:
        blob = dsviper.ValueBlob(zlib.decompress(base64.b64decode(mr.B64_DEFINITIONS)))
        defs = dsviper.Definitions.decode(blob)
        _DEFINITIONS = defs.const()
    return _DEFINITIONS

# Concept
class RuntimeIds:
    # Namespace Tuto
    Tuto_User: dsviper.ValueUUId = dsviper.ValueUUId.create("bfb135a1-49e6-132a-e693-b84be57e9726")
    Tuto_Status: dsviper.ValueUUId = dsviper.ValueUUId.create("38733635-4817-2af4-838c-a0fe77c65e53")
    Tuto_Account: dsviper.ValueUUId = dsviper.ValueUUId.create("da60982c-7ae3-6f6f-2052-8cf086fb13dc")
    Tuto_Identity: dsviper.ValueUUId = dsviper.ValueUUId.create("5ff52b96-4e51-7c9b-d934-c542f6ac9255")
    Tuto_Login: dsviper.ValueUUId = dsviper.ValueUUId.create("f223819a-167a-b9f8-e483-3abf4a0c2518")
    Tuto_Texture: dsviper.ValueUUId = dsviper.ValueUUId.create("dc4e365c-5641-2259-3853-65ee1de7ae69")
    Tuto_Thumbnail: dsviper.ValueUUId = dsviper.ValueUUId.create("54458468-e1d5-f9f1-b5df-cdf4d5c76cb2")
    pass

# Attachment
class AttachmentRuntimeIds:
    # Namespace Tuto
    Tuto_User_Account: dsviper.ValueUUId = dsviper.ValueUUId.create("ddff38a1-01b4-1979-d576-ca655a092bb8")
    Tuto_User_Avatar: dsviper.ValueUUId = dsviper.ValueUUId.create("0e866bc1-5074-3f2d-ef04-ae847fb115ff")
    Tuto_User_Identity: dsviper.ValueUUId = dsviper.ValueUUId.create("cc54d554-b8de-9960-cba3-40c04dc05b3a")
    Tuto_User_Login: dsviper.ValueUUId = dsviper.ValueUUId.create("438491ed-5518-5d0c-9836-920ee80dd0e8")
    Tuto_User_Portrait: dsviper.ValueUUId = dsviper.ValueUUId.create("f24b9e5f-f39a-98c3-7cce-ea08538b6d0b")
    pass