# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

import dsviper
from .data import *

