# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

import dsviper

Path_Root: dsviper.PathConst = dsviper.Path().const()

# Namespace Tuto
class Tuto_Path_Account:
    state: dsviper.PathConst = dsviper.Path.from_field("state").const()
    pass

class Tuto_Path_Identity:
    firstname: dsviper.PathConst = dsviper.Path.from_field("firstname").const()
    lastname: dsviper.PathConst = dsviper.Path.from_field("lastname").const()
    pass

class Tuto_Path_Login:
    nickname: dsviper.PathConst = dsviper.Path.from_field("nickname").const()
    password: dsviper.PathConst = dsviper.Path.from_field("password").const()
    pass

class Tuto_Path_Texture:
    width: dsviper.PathConst = dsviper.Path.from_field("width").const()
    height: dsviper.PathConst = dsviper.Path.from_field("height").const()
    pixels: dsviper.PathConst = dsviper.Path.from_field("pixels").const()
    pass

class Tuto_Path_Thumbnail:
    width: dsviper.PathConst = dsviper.Path.from_field("width").const()
    height: dsviper.PathConst = dsviper.Path.from_field("height").const()
    data: dsviper.PathConst = dsviper.Path.from_field("data").const()
    pass

