# Generated by kibo from model. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.10.jar

"""
Viper types for concepts, clubs, enums, structs and all containers defined for model.
"""

from __future__ import annotations
import dsviper
from . import definitions as md

__type_void: dsviper.TypeVoid | None = None
def type_void() -> dsviper.TypeVoid:
    global __type_void
    if __type_void is None:
        __type_void = dsviper.TypeVoid()
    return __type_void

# Numbers
__type_bool: dsviper.TypeBool | None = None
def type_bool() -> dsviper.TypeBool:
    global __type_bool
    if __type_bool is None:
        __type_bool = dsviper.TypeBool()
    return __type_bool


__type_uint8: dsviper.TypeUInt8 | None = None
def type_uint8() -> dsviper.TypeUInt8:
    global __type_uint8
    if __type_uint8 is None:
        __type_uint8 = dsviper.TypeUInt8()
    return __type_uint8


__type_uint16: dsviper.TypeUInt16 | None = None
def type_uint16() -> dsviper.TypeUInt16:
    global __type_uint16
    if __type_uint16 is None:
        __type_uint16 = dsviper.TypeUInt16()
    return __type_uint16


__type_uint32: dsviper.TypeUInt32 | None = None
def type_uint32() -> dsviper.TypeUInt32:
    global __type_uint32
    if __type_uint32 is None:
        __type_uint32 = dsviper.TypeUInt32()
    return __type_uint32


__type_uint64: dsviper.TypeUInt64 | None = None
def type_uint64() -> dsviper.TypeUInt64:
    global __type_uint64
    if __type_uint64 is None:
        __type_uint64 = dsviper.TypeUInt64()
    return __type_uint64


__type_int8: dsviper.TypeInt8 | None = None
def type_int8() -> dsviper.TypeInt8:
    global __type_int8
    if __type_int8 is None:
        __type_int8 = dsviper.TypeInt8()
    return __type_int8


__type_int16: dsviper.TypeInt16 | None = None
def type_int16() -> dsviper.TypeInt16:
    global __type_int16
    if __type_int16 is None:
        __type_int16 = dsviper.TypeInt16()
    return __type_int16


__type_int32: dsviper.TypeInt32 | None = None
def type_int32() -> dsviper.TypeInt32:
    global __type_int32
    if __type_int32 is None:
        __type_int32 = dsviper.TypeInt32()
    return __type_int32


__type_int64: dsviper.TypeInt64 | None = None
def type_int64() -> dsviper.TypeInt64:
    global __type_int64
    if __type_int64 is None:
        __type_int64 = dsviper.TypeInt64()
    return __type_int64


__type_float: dsviper.TypeFloat | None = None
def type_float() -> dsviper.TypeFloat:
    global __type_float
    if __type_float is None:
        __type_float = dsviper.TypeFloat()
    return __type_float


__type_double: dsviper.TypeDouble | None = None
def type_double() -> dsviper.TypeDouble:
    global __type_double
    if __type_double is None:
        __type_double = dsviper.TypeDouble()
    return __type_double


# Ids
__type_blob_id: dsviper.TypeBlobId | None = None
def type_blob_id() -> dsviper.TypeBlobId:
    global __type_blob_id
    if __type_blob_id is None:
        __type_blob_id = dsviper.TypeBlobId()
    return __type_blob_id


__type_commit_id: dsviper.TypeCommitId | None = None
def type_commit_id() -> dsviper.TypeCommitId:
    global __type_commit_id
    if __type_commit_id is None:
        __type_commit_id = dsviper.TypeCommitId()
    return __type_commit_id


__type_uuid: dsviper.TypeUUId | None = None
def type_uuid() -> dsviper.TypeUUId:
    global __type_uuid
    if __type_uuid is None:
        __type_uuid = dsviper.TypeUUId()
    return __type_uuid


# String & Blob
__type_string: dsviper.TypeString | None = None
def type_string() -> dsviper.TypeString:
    global __type_string
    if __type_string is None:
        __type_string = dsviper.TypeString()
    return __type_string


__type_blob: dsviper.TypeBlob | None = None
def type_blob() -> dsviper.TypeBlob:
    global __type_blob
    if __type_blob is None:
        __type_blob = dsviper.TypeBlob()
    return __type_blob


# Any
__type_any: dsviper.TypeAny | None = None
def type_any() -> dsviper.TypeAny:
    global __type_any
    if __type_any is None:
        __type_any = dsviper.TypeAny()
    return __type_any


# AnyConcept
__type_def_any_concept: dsviper.TypeAnyConcept | None = None
def type_def_any_concept() -> dsviper.TypeAnyConcept:
    global __type_def_any_concept
    if __type_def_any_concept is None:
        __type_def_any_concept = dsviper.TypeAnyConcept()
    return __type_def_any_concept

__type_AnyConceptKey: dsviper.TypeKey | None = None
def type_AnyConceptKey() -> dsviper.TypeKey:
    global __type_AnyConceptKey
    if __type_AnyConceptKey is None:
        __type_AnyConceptKey = dsviper.TypeKey(type_def_any_concept())
    return __type_AnyConceptKey

# Vecs

# Mats

# Tuples

# Optionals
__type_optional_AnyConceptKey: dsviper.TypeOptional | None = None
def type_optional_AnyConceptKey() -> dsviper.TypeOptional:
    global __type_optional_AnyConceptKey
    if __type_optional_AnyConceptKey is None:
        __type_optional_AnyConceptKey = dsviper.TypeOptional(type_AnyConceptKey())
    return __type_optional_AnyConceptKey


__type_optional_Tuto_Account: dsviper.TypeOptional | None = None
def type_optional_Tuto_Account() -> dsviper.TypeOptional:
    global __type_optional_Tuto_Account
    if __type_optional_Tuto_Account is None:
        __type_optional_Tuto_Account = dsviper.TypeOptional(type_Tuto_Account())
    return __type_optional_Tuto_Account


__type_optional_Tuto_Identity: dsviper.TypeOptional | None = None
def type_optional_Tuto_Identity() -> dsviper.TypeOptional:
    global __type_optional_Tuto_Identity
    if __type_optional_Tuto_Identity is None:
        __type_optional_Tuto_Identity = dsviper.TypeOptional(type_Tuto_Identity())
    return __type_optional_Tuto_Identity


__type_optional_Tuto_Login: dsviper.TypeOptional | None = None
def type_optional_Tuto_Login() -> dsviper.TypeOptional:
    global __type_optional_Tuto_Login
    if __type_optional_Tuto_Login is None:
        __type_optional_Tuto_Login = dsviper.TypeOptional(type_Tuto_Login())
    return __type_optional_Tuto_Login


__type_optional_Tuto_Texture: dsviper.TypeOptional | None = None
def type_optional_Tuto_Texture() -> dsviper.TypeOptional:
    global __type_optional_Tuto_Texture
    if __type_optional_Tuto_Texture is None:
        __type_optional_Tuto_Texture = dsviper.TypeOptional(type_Tuto_Texture())
    return __type_optional_Tuto_Texture


__type_optional_Tuto_Thumbnail: dsviper.TypeOptional | None = None
def type_optional_Tuto_Thumbnail() -> dsviper.TypeOptional:
    global __type_optional_Tuto_Thumbnail
    if __type_optional_Tuto_Thumbnail is None:
        __type_optional_Tuto_Thumbnail = dsviper.TypeOptional(type_Tuto_Thumbnail())
    return __type_optional_Tuto_Thumbnail


__type_optional_Tuto_UserKey: dsviper.TypeOptional | None = None
def type_optional_Tuto_UserKey() -> dsviper.TypeOptional:
    global __type_optional_Tuto_UserKey
    if __type_optional_Tuto_UserKey is None:
        __type_optional_Tuto_UserKey = dsviper.TypeOptional(type_Tuto_UserKey())
    return __type_optional_Tuto_UserKey



# Vectors

# Sets
__type_set_Tuto_UserKey: dsviper.TypeSet | None = None
def type_set_Tuto_UserKey() -> dsviper.TypeSet:
    global __type_set_Tuto_UserKey
    if __type_set_Tuto_UserKey is None:
        __type_set_Tuto_UserKey = dsviper.TypeSet(type_Tuto_UserKey())
    return __type_set_Tuto_UserKey



# Maps

# Sets

# Variants

# Namespace Tuto
__type_check_Tuto_UserKey: dsviper.TypeConcept | None = None
def type_check_Tuto_UserKey() -> dsviper.TypeConcept:
    global __type_check_Tuto_UserKey
    if __type_check_Tuto_UserKey is None:
        __type_check_Tuto_UserKey = md.definitions().check_concept(md.RuntimeIds.Tuto_User)
    return __type_check_Tuto_UserKey

__type_Tuto_UserKey: dsviper.TypeKey | None = None
def type_Tuto_UserKey() -> dsviper.TypeKey:
    global __type_Tuto_UserKey
    if __type_Tuto_UserKey is None:
        __type_Tuto_UserKey = dsviper.TypeKey(type_check_Tuto_UserKey())
    return __type_Tuto_UserKey


__type_Tuto_Status: dsviper.TypeEnumeration | None = None
def type_Tuto_Status() -> dsviper.TypeEnumeration:
    global __type_Tuto_Status
    if __type_Tuto_Status is None:
       __type_Tuto_Status =  md.definitions().check_enumeration(md.RuntimeIds.Tuto_Status)
    return __type_Tuto_Status


__type_Tuto_Account: dsviper.TypeStructure | None = None
def type_Tuto_Account() -> dsviper.TypeStructure:
    global __type_Tuto_Account
    if __type_Tuto_Account is None:
        __type_Tuto_Account = md.definitions().check_structure(md.RuntimeIds.Tuto_Account)
    return __type_Tuto_Account


__type_Tuto_Identity: dsviper.TypeStructure | None = None
def type_Tuto_Identity() -> dsviper.TypeStructure:
    global __type_Tuto_Identity
    if __type_Tuto_Identity is None:
        __type_Tuto_Identity = md.definitions().check_structure(md.RuntimeIds.Tuto_Identity)
    return __type_Tuto_Identity


__type_Tuto_Login: dsviper.TypeStructure | None = None
def type_Tuto_Login() -> dsviper.TypeStructure:
    global __type_Tuto_Login
    if __type_Tuto_Login is None:
        __type_Tuto_Login = md.definitions().check_structure(md.RuntimeIds.Tuto_Login)
    return __type_Tuto_Login


__type_Tuto_Texture: dsviper.TypeStructure | None = None
def type_Tuto_Texture() -> dsviper.TypeStructure:
    global __type_Tuto_Texture
    if __type_Tuto_Texture is None:
        __type_Tuto_Texture = md.definitions().check_structure(md.RuntimeIds.Tuto_Texture)
    return __type_Tuto_Texture


__type_Tuto_Thumbnail: dsviper.TypeStructure | None = None
def type_Tuto_Thumbnail() -> dsviper.TypeStructure:
    global __type_Tuto_Thumbnail
    if __type_Tuto_Thumbnail is None:
        __type_Tuto_Thumbnail = md.definitions().check_structure(md.RuntimeIds.Tuto_Thumbnail)
    return __type_Tuto_Thumbnail


__attachment_Tuto_User_Account: dsviper.Attachment | None = None
def attachment_Tuto_User_Account() -> dsviper.Attachment:
    global __attachment_Tuto_User_Account
    if __attachment_Tuto_User_Account is None:
        __attachment_Tuto_User_Account = md.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Account)
    return __attachment_Tuto_User_Account


__attachment_Tuto_User_Avatar: dsviper.Attachment | None = None
def attachment_Tuto_User_Avatar() -> dsviper.Attachment:
    global __attachment_Tuto_User_Avatar
    if __attachment_Tuto_User_Avatar is None:
        __attachment_Tuto_User_Avatar = md.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Avatar)
    return __attachment_Tuto_User_Avatar


__attachment_Tuto_User_Identity: dsviper.Attachment | None = None
def attachment_Tuto_User_Identity() -> dsviper.Attachment:
    global __attachment_Tuto_User_Identity
    if __attachment_Tuto_User_Identity is None:
        __attachment_Tuto_User_Identity = md.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Identity)
    return __attachment_Tuto_User_Identity


__attachment_Tuto_User_Login: dsviper.Attachment | None = None
def attachment_Tuto_User_Login() -> dsviper.Attachment:
    global __attachment_Tuto_User_Login
    if __attachment_Tuto_User_Login is None:
        __attachment_Tuto_User_Login = md.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Login)
    return __attachment_Tuto_User_Login


__attachment_Tuto_User_Portrait: dsviper.Attachment | None = None
def attachment_Tuto_User_Portrait() -> dsviper.Attachment:
    global __attachment_Tuto_User_Portrait
    if __attachment_Tuto_User_Portrait is None:
        __attachment_Tuto_User_Portrait = md.definitions().check_attachment(md.AttachmentRuntimeIds.Tuto_User_Portrait)
    return __attachment_Tuto_User_Portrait


