# Generated by kibo from model. Do not edit by hand.
# Templates: kibo-template-viper 1.2.5 (MIT).
# Runtime: this file imports `dsviper`,
# distributed under LicenseRef-DigitalSubstrate-Commercial-1.2.
# Commercial use requires a Commercial Licence from Digital Substrate.
# Generated from model.dsm.json by kibo-1.2.13.jar

import dsviper
from .data import *

