#!/usr/bin/env python3
"""Generate source/_static/llms.txt from source/**/*.md + template + overrides.

Reads first H1 (title) and first paragraph (description) from each
MyST/Markdown source file, applies per-URL overrides, expands
`{{auto:<glob>}}` markers in the template into bulleted lists.

Usage:
  python tools/build_llms_txt.py            Write source/_static/llms.txt.
  python tools/build_llms_txt.py --check    Regenerate to memory and diff
                                            against committed file.
                                            Exit 1 on drift.

The script is stdlib-only on purpose (Sphinx's tool chain already requires
no extra dependencies for the build).

Symmetric counterpart of the devkit-website script that produces the
landing-page llms.txt — same template/overrides format.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "source"
TEMPLATE = ROOT / "tools" / "llms_txt" / "template.md"
OVERRIDES = ROOT / "tools" / "llms_txt" / "overrides.toml"
OUTPUT = SOURCE_DIR / "_static" / "llms.txt"

# Canonical online doc site. Hardcoded — llms.txt URLs must point at the
# production host regardless of where it was generated.
DOC_URL = "https://docs.digitalsubstrate.io"

HEADER = (
    "<!-- Generated by tools/build_llms_txt.py from tools/llms_txt/{template.md,overrides.toml}. -->\n"
    "<!-- Edit those, not this file. Run `python tools/build_llms_txt.py` to regenerate. -->\n"
    "\n"
)


# ---------- Page discovery ----------

# Strip a leading MyST frontmatter block if present (--- ... ---).
_FRONTMATTER_RE = re.compile(r"\A---\s*\n.*?\n---\s*\n", re.DOTALL)
# Match the first H1: a line starting with exactly one '# '.
_H1_RE = re.compile(r"^# +(.+?)\s*$", re.MULTILINE)


@dataclass
class Page:
    src: Path           # repo-relative POSIX path to .md
    url: str            # full https URL (production host)
    title: str
    description: str
    sort: int | None
    skip: bool


def _url_from_path(md_path: Path) -> str:
    """source/foo/bar.md → https://docs.digitalsubstrate.io/foo/bar.html"""
    rel = md_path.relative_to(SOURCE_DIR).with_suffix(".html")
    return f"{DOC_URL}/{rel.as_posix()}"


def _parse_md(md_path: Path) -> tuple[str, str] | None:
    """Return (title, description) or None if no H1 is found.

    Title = text of the first `# Heading` line.
    Description = the paragraph immediately following the H1 (joined with
    spaces, with line breaks collapsed). Skipped if the next non-blank
    block is a directive (` ```{...} `), MyST role, or HTML comment —
    those are not human-readable summaries.
    """
    text = md_path.read_text()
    text = _FRONTMATTER_RE.sub("", text, count=1)

    h1 = _H1_RE.search(text)
    if not h1:
        return None
    title = h1.group(1).strip()

    after = text[h1.end():].lstrip("\n")
    # Take everything up to the next blank line as the description block.
    para_lines: list[str] = []
    for line in after.splitlines():
        if not line.strip():
            break
        para_lines.append(line.rstrip())
    if not para_lines:
        return title, ""

    first = para_lines[0].lstrip()
    # Heuristic: directives, HTML, headings — not prose.
    if first.startswith(("```", "<!--", "<", "#", ":", "{")):
        return title, ""

    description = " ".join(para_lines)
    # Strip MyST inline roles like {term}`x` / {doc}`x` for a cleaner one-liner.
    description = re.sub(r"\{[a-z]+\}`([^`]*)`", r"\1", description)
    # Strip inline backticks and asterisks (don't render as markdown inside a list item).
    description = description.replace("`", "").replace("**", "").replace("*", "")
    return title, description


def discover_pages(overrides: dict) -> dict[str, Page]:
    pages: dict[str, Page] = {}
    for md_path in sorted(SOURCE_DIR.rglob("*.md")):
        # Skip files under _static / _templates / _ext / _fixtures.
        if any(part.startswith("_") for part in md_path.relative_to(SOURCE_DIR).parts):
            continue
        parsed = _parse_md(md_path)
        if parsed is None:
            continue
        title, description = parsed
        rel_src = md_path.relative_to(ROOT).as_posix()
        url = _url_from_path(md_path)

        ov = overrides.get(url, {})
        title = ov.get("title", title)
        description = ov.get("description", description)

        pages[rel_src] = Page(
            src=Path(rel_src),
            url=url,
            title=title,
            description=description,
            sort=ov.get("sort"),
            skip=ov.get("skip", False),
        )
    return pages


# ---------- Template expansion ----------

_AUTO_MARKER_RE = re.compile(r"\{\{auto:([^}]+)\}\}")


def _expand_glob(pattern: str, pages: dict[str, Page]) -> list[Page]:
    from fnmatch import fnmatch
    chunks = [c.strip() for c in pattern.split(",") if c.strip()]
    seen: set[str] = set()
    ordered: list[Page] = []
    for chunk in chunks:
        matches: list[Page] = []
        for path_str, page in pages.items():
            if page.skip or path_str in seen:
                continue
            if fnmatch(path_str, chunk):
                matches.append(page)
                seen.add(path_str)
        matches.sort(key=lambda p: (p.sort if p.sort is not None else 10_000, p.url))
        ordered.extend(matches)
    return ordered


def _render_bullet(page: Page) -> str:
    desc = page.description.strip()
    if desc:
        return f"- [{page.title}]({page.url}): {desc}"
    return f"- [{page.title}]({page.url})"


def render(template_text: str, pages: dict[str, Page]) -> str:
    def replace(m: re.Match) -> str:
        pattern = m.group(1).strip()
        matched = _expand_glob(pattern, pages)
        if not matched:
            return f"<!-- WARNING: {{{{auto:{pattern}}}}} matched no pages -->"
        return "\n".join(_render_bullet(p) for p in matched)

    return _AUTO_MARKER_RE.sub(replace, template_text)


def check_for_unreferenced(template_text: str, pages: dict[str, Page]) -> list[str]:
    from fnmatch import fnmatch
    referenced: set[str] = set()
    for m in _AUTO_MARKER_RE.finditer(template_text):
        chunks = [c.strip() for c in m.group(1).split(",") if c.strip()]
        for path_str in pages:
            for chunk in chunks:
                if fnmatch(path_str, chunk):
                    referenced.add(path_str)
                    break
    return [p.url for path_str, p in pages.items()
            if not p.skip and path_str not in referenced]


# ---------- Main ----------

def load_overrides() -> dict:
    if not OVERRIDES.is_file():
        return {}
    data = tomllib.loads(OVERRIDES.read_text())
    return data.get("overrides", {})


def generate() -> str:
    if not TEMPLATE.is_file():
        sys.exit(f"Template not found: {TEMPLATE}")
    overrides = load_overrides()
    pages = discover_pages(overrides)
    template_text = TEMPLATE.read_text()
    body = render(template_text, pages)

    unreferenced = check_for_unreferenced(template_text, pages)
    if unreferenced:
        warning = (
            "<!-- WARNING: pages discovered but not referenced by any "
            "{{auto:...}} marker (add to template or set skip=true in "
            f"overrides.toml): {', '.join(unreferenced)} -->\n"
        )
        body = warning + body

    return HEADER + body


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate source/_static/llms.txt.")
    parser.add_argument("--check", action="store_true",
                        help="Regenerate to memory and diff against committed file. Exit 1 on drift.")
    args = parser.parse_args()

    generated = generate()

    if args.check:
        if not OUTPUT.is_file():
            print(f"Missing: {OUTPUT}. Run `python tools/build_llms_txt.py` to create it.",
                  file=sys.stderr)
            sys.exit(1)
        existing = OUTPUT.read_text()
        if existing != generated:
            diff = difflib.unified_diff(
                existing.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=str(OUTPUT.relative_to(ROOT)),
                tofile="<generated>",
            )
            sys.stderr.write("".join(diff))
            sys.stderr.write(
                "\nllms.txt drift detected. Run `python tools/build_llms_txt.py` and commit.\n"
            )
            sys.exit(1)
        print(f"OK: {OUTPUT.relative_to(ROOT)} is up to date.")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(generated)} bytes).")


if __name__ == "__main__":
    main()
