#!/usr/bin/env python3
"""Generate llms-full.txt — full-content companion to llms.txt.

Follows the convention at https://llmstxt.org/ : llms.txt is a curated
index with links and descriptions; llms-full.txt is the same structure
with the full content of each page inlined, so an LLM can answer
product questions from a single fetch without traversing the link graph.

The output is parallel to llms.txt by construction: this script reads
the same template (tools/llms_txt/template.md) and the same overrides
(tools/llms_txt/overrides.toml) as build_llms_txt.py, and expands the
`{{auto:<glob>}}` markers — but inlines each matched page's full
Markdown body instead of rendering a bullet. Section headings and
prose between markers are preserved verbatim.

Each inlined page is preceded by a `<!-- FILE: <source-path> -->`
marker so an LLM can cite precise sources while keeping the document
valid Markdown.

Excluded from inlining:
  - dsviper/api/generated/*  — autosummary stubs (noisy reference)
  - source/legal/*           — license/notice text (not useful for Q&A)

Usage:
  python tools/build_llms_full.py
      Writes build/html/llms-full.txt (next to Sphinx HTML output).
  python tools/build_llms_full.py --out PATH
      Writes to PATH instead.

Also exposed via `make llmsfulltxt`. Wired into `make html` through a
build-finished hook in source/conf.py, so a vanilla Sphinx build
produces llms-full.txt automatically.

Stdlib-only on purpose, like build_llms_txt.py — no new dependency
introduced for what is fundamentally a concatenation.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Reuse page discovery and template parsing from the llms.txt builder
# so the two outputs stay structurally aligned.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_llms_txt import (  # noqa: E402
    ROOT,
    TEMPLATE,
    _AUTO_MARKER_RE,
    _expand_glob,
    discover_pages,
    load_overrides,
)

DEFAULT_OUT = ROOT / "build" / "html" / "llms-full.txt"

HEADER = (
    "<!-- Generated by tools/build_llms_full.py. -->\n"
    "<!-- Full-content companion to llms.txt — see https://llmstxt.org/. -->\n"
    "<!-- Each page is preceded by a <!-- FILE: <path> --> marker for citation. -->\n"
    "\n"
)

_EXCLUDED_PREFIXES = (
    "source/legal/",
)
_EXCLUDED_SUBSTRINGS = (
    "dsviper/api/generated/",
)


def _is_excluded(rel_src: str) -> bool:
    if rel_src.startswith(_EXCLUDED_PREFIXES):
        return True
    return any(s in rel_src for s in _EXCLUDED_SUBSTRINGS)


def _inline_page(rel_src: str) -> str:
    body = (ROOT / rel_src).read_text(encoding="utf-8").rstrip()
    return f"\n<!-- FILE: {rel_src} -->\n\n{body}\n"


def render(template_text: str, pages: dict) -> str:
    def replace(m: re.Match) -> str:
        pattern = m.group(1).strip()
        matched = _expand_glob(pattern, pages)
        kept = [p for p in matched if not _is_excluded(p.src.as_posix())]
        if not kept:
            return f"<!-- (no pages for {pattern}) -->"
        return "".join(_inline_page(p.src.as_posix()) for p in kept)

    return _AUTO_MARKER_RE.sub(replace, template_text)


def generate() -> str:
    if not TEMPLATE.is_file():
        sys.exit(f"Template not found: {TEMPLATE}")
    overrides = load_overrides()
    pages = discover_pages(overrides)
    body = render(TEMPLATE.read_text(), pages)
    return HEADER + body


def write(out: Path) -> int:
    text = generate()
    out.parent.mkdir(parents=True, exist_ok=True)
    encoded = text.encode("utf-8")
    out.write_bytes(encoded)
    return len(encoded)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate llms-full.txt.")
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output path (default: {DEFAULT_OUT.relative_to(ROOT)}).",
    )
    args = parser.parse_args()

    size = write(args.out)
    try:
        printable = args.out.relative_to(ROOT)
    except ValueError:
        printable = args.out
    print(f"Wrote {printable} ({size} bytes).")


if __name__ == "__main__":
    main()
